version: "3.8"

services:
  app:
    build:
      context: .
    ports:
      - "8001:8001"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://iotuser:iotpass@db:5432/iot_sensors_project
    volumes:
      - .:/app

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: iotuser
      POSTGRES_PASSWORD: iotpass
      POSTGRES_DB: iot_sensors_project
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/database_backup_with_data.sql:/docker-entrypoint-initdb.d/database_backup_with_data.sql:ro

volumes:
  postgres_data:
